Repository Jagusti/fvtt-wfrp4e-gmtoolkit, pull requests merged in 2022-09, with the labels that each got.

#168 Add Damage Console
  apps/damage.js
  assets/icons/deal-damage.svg
  css/gmtoolkit.css
  lang/de.json
  lang/en.json
  lang/fr.json
  lang/ja.json
  packs/gm-toolkit-macros.db
  scripts/macros/apply-basic-damage.js
  scripts/macros/launch-damage-console.js
  scripts/macros/macro-toolbox.js
  templates/damage.hbs
  templates/group-test.hbs
  wfrp4e-gm-toolkit.mjs
Labels: enhancement

#169 Add release workflow
  .github/workflows/main.yml
Labels: maintenance

#171 Add Discord contact to templates; Move PR template
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue_report.md
  .github/pull_request_template.md
Labels: maintenance

#173 6.0.0 Release
  CHANGELOG.md
  module.json
  packs/gm-toolkit-macros.db
  scripts/macros/launch-damage-console.js
  scripts/macros/macro-toolbox.js
Labels: maintenance

#178 Add current version and key features to readme
  CHANGELOG.md
  README.md
Labels: documentation

#179 Add localization string for Launch Damage Console
  CHANGELOG.md
  lang/de.json
  lang/en.json
  lang/fr.json
  lang/ja.json
Labels: localization

#180 Show macro version from compendium in Toolkit Maintenance #176
  CHANGELOG.md
  apps/gm-toolkit-maintenance.js
Labels: bug

#181 Add macro hotbar shortcut upgrade advice
  CHANGELOG.md
  README.md
Labels: documentation

#185 Pause for players when running Session Turnover #182
  CHANGELOG.md
  packs/gm-toolkit-macros.db
  scripts/macros/session-turnover.js
Labels: bug

#188 PL translation and fix for group advantages without a combat
  CHANGELOG.md
  lang/pl.json
  module.json
  modules/utility.mjs
Labels: bug, localization
