Repository Jagusti/fvtt-wfrp4e-gmtoolkit, pull requests merged in 2022-07, with the labels that each got.

#120 Update Reset Fortune macro to use "party" group selection
  CHANGELOG.md
  packs/gm-toolkit-macros.db
  scripts/macros/reset-fortune.js
Labels: bug

#121 Use actors and tokens for Dark Whisper target selection #58
  CHANGELOG.md
  lang/en.json
  lang/fr.json
  lang/ja.json
  modules/gm-toolkit-settings.mjs
  scripts/macros/dark-whispers.js
Labels: enhancement

#123 Use system localization keys where available #110
  CHANGELOG.md
  lang/en.json
  lang/fr.json
  lang/ja.json
  modules/token-hud-extension.mjs
  modules/utility.mjs
  packs/gm-toolkit-macros.db
  scripts/macros/dark-whispers.js
  scripts/macros/reset-fortune.js
  scripts/macros/set-token-vision-light.js
Labels: enhancement

#124 Extend Make Secret Group Tests macro beyond party #61
  CHANGELOG.md
  assets/icons/make-secret-group-test.svg
  lang/en.json
  lang/fr.json
  lang/ja.json
  packs/gm-toolkit-macros.db
  scripts/macros/make-secret-group-test.js
  scripts/macros/make-secret-party-test.js
Labels: enhancement

#126 Add test difficulty option for roll dialog bypass
  CHANGELOG.md
  apps/group-test.js
  modules/gm-toolkit-settings.mjs
  modules/group-test.mjs
  templates/group-test.hbs
Labels: enhancement

#127 Step-adjust test difficulty on fallback
  CHANGELOG.md
  lang/en.json
  lang/fr.json
  lang/ja.json
  modules/gm-toolkit-settings.mjs
  modules/group-test.mjs
Labels: enhancement

#128 Summarise group skill check results in chatlog #62
  CHANGELOG.md
  modules/gm-toolkit-settings.mjs
  modules/group-test.mjs
Labels: enhancement

#132 Fix Token Hud Extension not rendering bug
  CHANGELOG.md
  modules/token-hud-extension.mjs
  wfrp4e-gm-toolkit.mjs
Labels: bug

#137 Fix not being able to respond to Dark Whispers
  wfrp4e-gm-toolkit.mjs
Labels: bug

#138 Add macro to Check Conditions at end of round
  CHANGELOG.md
  assets/icons/aura-conditions.svg
  lang/en.json
  lang/fr.json
  lang/ja.json
  packs/gm-toolkit-macros.db
  scripts/macros/check-conditions.js
  scripts/macros/macro-toolbox.js
Labels: enhancement, localization

#139 Add Spectator and Group Type translations (ja)
  CHANGELOG.md
  lang/ja.json
Labels: localization

#141 Add localization for Group Tests and Check Conditions
  CHANGELOG.md
  lang/en.json
  lang/fr.json
  lang/ja.json
  modules/group-test.mjs
  packs/gm-toolkit-macros.db
  scripts/macros/check-conditions.js
Labels: localization

#144 Add German localisation
  CHANGELOG.md
  lang/de.json
Labels: localization

#146 Add compatibility with Babele #135
  modules/gm-toolkit-settings.mjs
  wfrp4e-gm-toolkit.mjs
Labels: bug, compatibility

#152 Add GM check for advantage scenarios
  CHANGELOG.md
  modules/advantage.mjs
Labels: bug
