Repository Jagusti/fvtt-wfrp4e-gmtoolkit, pull requests merged in 2022-01, with the labels that each got.

#73 Add RollTable compatibility for Send Dark Whispers macro
  CHANGELOG.md
  lang/en.json
  lang/fr.json
  module.json
  packs/gm-toolkit-macros.db
  packs/gm-toolkit-tables.db
  scripts/macros/dark-whispers.js
Labels: compatibility

#74 Add RollTable compatibility for Token Hud Extension shortcuts
  CHANGELOG.md
  lang/en.json
  lang/fr.json
  modules/token-hud-extension.mjs
Labels: compatibility

#76 Add FVTT v9 compatibility for Set Token Vision and Light macro
  CHANGELOG.md
  lang/en.json
  packs/gm-toolkit-macros.db
  scripts/macros/set-token-vision-light.js
Labels: compatibility

#75 Add FVTT v9 and WFRP v5 Compatibility
  CHANGELOG.md
  README.md
  lang/en.json
  lang/fr.json
  module.json
  modules/gm-toolkit-settings.mjs
  modules/token-hud-extension.mjs
  packs/gm-toolkit-macros.db
  packs/gm-toolkit-tables.db
  scripts/macros/dark-whispers.js
  scripts/macros/set-token-vision-light.js
Labels: compatibility

#79 Dark Whispers updates
  packs/gm-toolkit-macros.db
  packs/gm-toolkit-tables.db
Labels: bug, enhancement

#82 Fix Token Hud Extension for players with token config permission #67
  CHANGELOG.md
  css/gmtoolkit.css
  modules/token-hud-extension.mjs
Labels: bug

#83 Add Advantage automation for winning opposed tests
  CHANGELOG.md
  lang/en.json
  lang/fr.json
  modules/advantage.mjs
  modules/gm-toolkit-settings.mjs
  modules/gm-toolkit.mjs
  modules/utility.mjs
Labels: enhancement

#84 Clear Advantage when suffering a condition
  CHANGELOG.md
  lang/en.json
  lang/fr.json
  modules/advantage.mjs
  modules/gm-toolkit-settings.mjs
  modules/utility.mjs
Labels: enhancement

#86 Add compatibility with Advanced Macros
  CHANGELOG.md
  packs/gm-toolkit-macros.db
  scripts/macros/add-xp.js
  scripts/macros/reset-fortune.js
  scripts/macros/session-turnover.js
Labels: compatibility
