Repository Jagusti/fvtt-wfrp4e-gmtoolkit, pull requests merged in 2023-04, with the labels that each got.

#214 Correctly identify non-combatant actors
  CHANGELOG.md
  modules/utility.mjs
Labels: bug

#217 Fix broken advantage automation
  modules/advantage.mjs
  modules/utility.mjs
Labels: bug

#189 New macro: Change scene to yards
  CHANGELOG.md
  assets/icons/scale-map.svg
  lang/de.json
  lang/en.json
  lang/fr.json
  lang/ja.json
  lang/pl.json
  packs/gm-toolkit-macros.db
  scripts/macros/change-scene-to-yards.js
  scripts/macros/macro-toolbox.js
Labels: enhancement

#219 Tweak Token Vision and Light settings
  CHANGELOG.md
  packs/gm-toolkit-macros.db
  scripts/macros/set-token-vision-light.js
Labels: enhancement

#221 6.0.3 Release
  module.json
Labels: maintenance
